session_name: cli-pm
start_directory: /Volumes/External/Users/sanifss/Desktop/Workspace/Projects/Personal/cli-pm
windows:
- window_name: editor
  panes:
  - shell_command:
    - nvim .
  layout: 55e5,230x40,0,0,16
- window_name: Claude
  panes:
  - shell_command:
    - claude
  layout: 55e6,230x40,0,0,17
- window_name: Git
  panes:
  - shell_command:
    - lazygit
  layout: 55e7,230x40,0,0,18
- window_name: shell
  panes:
  - shell_command: []
  layout: d5e0,230x40,0,0,21
